jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make the start of the program an executable
      run: |
        chmod +x CargoHub/start-system.sh
    - name: Run Start-system to let the program run
      run: |
        CargoHub/start-system.sh &
        sleep 5
    - name: Make integration-test.sh executable
      run: |
        chmod +x CargoHub/Integration-Tests/integration-test.sh
    - name: Run integration tests with integration-test.sh
      run: |
        CargoHub/Integration-Tests/integration-test.sh
    - name: Run integration tests with pytest
      run: |
        pytest CargoHub/Integration-Tests --cov=CargoHub/api --cov-report xml:coverage.xml
    - name: Stop the server
      run: |
        pkill -f CargoHub/api/main.py || true
    - name: Store coverage report
      uses: actions/upload-artifact@v4
      with:
        path: coverage.xml
      if: ${{ failure() }}
